default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "Council"

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
  enable_frontend_error_catching: true

staging:
  <<: *defaults
  active: true
  enable_frontend_error_catching: true
